name: 'CI - Rust'

on:
  workflow_dispatch:

  pull_request:
    paths:
      - 'rust/**'
  push:
    paths:
      - 'rust/**'

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        rust: [ stable ]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
    - name: Run tests
      run: |
        cd rust
        cargo build
        cargo test -- --nocapture
