name: Nightly
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      version:
        description: Nightly version number (e.g. 20221125)
        required: true
        type: string

jobs:
  ruby:
    name: Ruby Gems
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gem:
          - selenium-devtools
          - selenium-webdriver
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
      - uses: p0deje/setup-bazel@0.2.0
        with:
          bazelisk-cache: true
          disk-cache: rb-${{ matrix.gem }}
          external-cache: |
            name: rb-${{ matrix.gem }}
            manifest:
              crates: rust/Cargo.Bazel.lock
              npm: package-lock.json
              pypi__pip: py/requirements_lock.txt
              rules_ruby_dist: rb/ruby_version.bzl
          repository-cache: true
      - run: bazel run //rb:${{ matrix.gem }}-bump-nightly-version ${{ inputs.version }}
      - run: bazel run //rb:${{ matrix.gem }}-release-nightly
        env:
          GEM_HOST_API_KEY: Bearer ${{ secrets.GITHUB_TOKEN }}
